import type { Metadata } from "next";
import { ArrowRight, CalendarDays, ClipboardCheck, UsersRound } from "lucide-react";
import { PageIntro } from "@/components/page-parts";
import { LeadForm } from "@/components/lead-form";

export const metadata: Metadata = { title: "Hajj Guidance & Consultation", description: "Speak with Al Faroque Tours and Travels about Hajj registration, preparation and travel requirements for Indian pilgrims." };

export default function HajjPage() {
  return <><PageIntro eyebrow="HAJJ · GUIDANCE & INQUIRY" title={<>A sacred journey<br /><em>needs careful planning.</em></>} description="Hajj registration and travel arrangements depend on current official rules and quotas. Our team can help you understand the process and what to prepare."><a className="button button-primary" href="#hajj-inquiry">Request a consultation <ArrowRight size={17} /></a></PageIntro><section className="section plain-section"><div className="wrap"><div className="section-head"><div><p className="eyebrow">START WITH CLARITY</p><h2>Three steps to a<br />well-prepared inquiry.</h2></div><p className="section-aside">We’ll explain what’s current, what’s required and where you should verify official guidance.</p></div><div className="process-grid"><article><CalendarDays /><span>01</span><h3>Share your plans</h3><p>Tell us your preferred year, city and who will be travelling.</p></article><article><ClipboardCheck /><span>02</span><h3>Review requirements</h3><p>We’ll discuss current eligibility and required documents. Rules may change each season.</p></article><article><UsersRound /><span>03</span><h3>Speak with our team</h3><p>Get a personal consultation before making a registration or payment decision.</p></article></div><div className="hajj-callout"><strong>Important</strong><p>Hajj registration, eligibility, quotas, package authorization and payment must follow current Government of India and Saudi Ministry of Hajj requirements. We do not guarantee allocation.</p></div></div></section><section className="section form-band" id="hajj-inquiry"><div className="wrap consultation-layout"><div><p className="eyebrow">HAJJ CONSULTATION</p><h2>Talk it through<br /><em>with a real person.</em></h2><p>Leave your WhatsApp number and our team will contact you about your inquiry.</p><a href="tel:+919691017171" className="text-link">Call +91 96910 17171 <ArrowRight size={17} /></a></div><div className="consultation-form"><LeadForm inquiryType="hajj" /></div></div></section></>;
}