import type { Metadata } from "next";
import { Clock3, MapPin, MessageCircle, Phone } from "lucide-react";
import { PageIntro } from "@/components/page-parts";
import { LeadForm } from "@/components/lead-form";

export const metadata: Metadata = { title: "Contact Al Farooque Travels", description: "Speak with Al Farooque Travels in Burhanpur, Madhya Pradesh. Call or WhatsApp +91 96910 17171." };

export default function ContactPage() {
  return <><PageIntro eyebrow="WE'RE HERE TO HELP" title={<>A real person.<br /><em>A thoughtful answer.</em></>} description="Tell us where you’re hoping to go. Our Burhanpur team will help you understand the next step."><a className="button button-primary" href="https://wa.me/919691017171" target="_blank" rel="noreferrer"><MessageCircle size={17} /> Message on WhatsApp</a></PageIntro><section className="section plain-section"><div className="wrap contact-layout"><div className="contact-details"><p className="eyebrow">COME SAY SALAAM</p><h2>Based in Burhanpur.<br />Here for your journey.</h2><div className="contact-item"><MapPin /><div><b>Our office</b><p>Nizamuddin Gate, Azad Nagar<br />Burhanpur, Madhya Pradesh 450331<br />India</p></div></div><div className="contact-item"><Phone /><div><b>Call our team</b><a href="tel:+919691017171">+91 96910 17171</a></div></div><div className="contact-item"><MessageCircle /><div><b>WhatsApp</b><a href="https://wa.me/919691017171" target="_blank" rel="noreferrer">Start a conversation</a></div></div><div className="contact-item"><Clock3 /><div><b>Office hours</b><p>Monday–Saturday · 10:00 am–6:00 pm IST<br />Please call before visiting.</p></div></div><div className="map-frame"><iframe title="Al Farooque Travels office area in Burhanpur" src="https://maps.google.com/maps?q=Nizamuddin%20Gate%2C%20Azad%20Nagar%2C%20Burhanpur%2C%20Madhya%20Pradesh%20450331&t=&z=14&ie=UTF8&iwloc=&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><a href="https://maps.google.com/?q=Nizamuddin+Gate,+Azad+Nagar,+Burhanpur,+Madhya+Pradesh+450331" target="_blank" rel="noreferrer">Open in Google Maps ↗</a></div></div><div className="contact-form-panel"><p className="eyebrow">SEND AN INQUIRY</p><h2>What can we help<br />you plan?</h2><p>Leave your WhatsApp number and our team will follow up.</p><LeadForm inquiryType="general" /></div></div></section></>;
}